server:
  port: 8081

spring:
  application:
    name: dubbo-consumer

logging:
  path: /home/admin/var/dubbo-consumer/
  level:
    root: info
    org.springframework.web: info

zipkin:
  url: http://127.0.0.1:9411/api/v2/spans
  connectTimeout: 5000
  readTimeout: 10000
  # 取样率，指的是多次请求中有百分之多少传到zipkin。例如 1.0 是全部取样，0.5是 50% 取样
  rate: 1.0f