server:
  port: 10881

spring:
  application:
    name: dubbo-consumer
  security:
    basic:
      path: /swagger-ui.html,/v2/api-docs # 拦截的路径
    user:
      name: admin # 配置用户名
      password: admin  #密码
  boot:
    admin:
      enabled: true
      client:
        instance:
          name: ${spring.application.name}
          prefer-ip: true
        url: http://127.0.0.1:3333
  redis:
    host: 127.0.0.1
    database: 0
    password: foobared
    timeout: 3000
    jedis:
      pool:
        max-idle: 4
        max-active: 8
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  path: /home/admin/var/dubbo-consumer/
  level:
    root: info
    org.springframework.web: info

zipkin:
  url: http://127.0.0.1:9411/api/v2/spans
  connectTimeout: 5000
  readTimeout: 10000
  # 取样率，指的是多次请求中有百分之多少传到zipkin。例如 1.0 是全部取样，0.5是 50% 取样
  rate: 1.0f