server:
  port: 8081

spring:
  application:
    name: dubbo-consumer

logging:
  path: /home/admin/var/dubbo-consumer/
  level:
    root: info
    org.springframework.web: info

zipkin:
  url: http://192.168.3.42:9411
  connectTimeout: 5000
  readTimeout: 10000
  serviceName: JMCui